version: 0.2

phases:
  build:
    commands:
      - echo phase
      - mvn clean package 
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/stack.jar
  discard-paths: yes